# Basic
title: Vic_Wei
subtitle: 端正态度，提升能力
welcome_message: 感谢您访问iOS开发者：Vic_Wei的博客
description: Stay hungry, Stay foolish!
creator: <a href="http://www.weikun.info">@Vic_Wei</a>

url: "http://www.weikun.info"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: '#'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Vic_Wei
    # duoshuo: 
    
# Social
social:
    weibo: ''
    github: ''
    twitter: ''
    gplus: 107108267983477358170
    mail: w_k0205@sina.cn

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
